# EXAMPLE 1 - IRIS DATASET 

Based on https://groups.google.com/g/what-if-tool/c/rJfRorMqODc?pli=1

The issue is that WIT was made for Tensor Flow models and need some adaptation to work with Sklearn

In [1]:
from sklearn.datasets import load_iris 
iris = load_iris()
X = iris.data  
Y = iris.target


In [2]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(
    X, Y, test_size=0.2
)



In [3]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e4)
logreg.fit(train_x, train_y)





C:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10000.0)

In [4]:
# adaptation between tensor to sklearn/pandas
def logreg_pred(testset):
    probs = logreg.predict_proba(testset[:, :-1])
    return prob.tolist()

import numpy as np
test_examples = np.hstack((test_x,
                           test_y.reshape(-1,1)))

In [5]:
!pip install --upgrade witwidget

In [6]:
from witwidget.notebook.visualization import WitConfigBuilder
config_builder = WitConfigBuilder(
    test_examples.tolist(),
    feature_names=['petal length', 'petal width', 'sepal length', 'sepal width', 'species'])\
.set_custom_predict_fn(logreg_pred).set_target_feature('species')

In [7]:
from witwidget.notebook.visualization import WitWidget
WitWidget(config_builder, height=600)

WitWidget(config={'model_type': 'classification', 'label_vocab': [], 'feature_names': ['petal length', 'petal …

# EXAMPLE 2 - GERMAN CREDIT DATASET


In [8]:
!pip install dalex

In [9]:
import dalex as dx
import pandas as pd
data = dx.datasets.load_german()
data

risk     sex  job housing saving_accounts checking_account  \
0       1    male    2     own       not_known           little   
1       0  female    2     own          little         moderate   
2       1    male    1     own          little        not_known   
3       1    male    2    free          little           little   
4       0    male    2    free          little           little   
..    ...     ...  ...     ...             ...              ...   
995     1  female    1     own          little        not_known   
996     1    male    3     own          little           little   
997     1    male    2     own          little        not_known   
998     0    male    2    free          little           little   
999     1    male    2     own        moderate         moderate   

     credit_amount  duration              purpose  age  
0             1169         6             radio/TV   67  
1             5951        48             radio/TV   22  
2             2096        12            education   49  
3             7882        42  furniture/equipment   45  
4             4870        24                  car   53  
..             ...       ...                  ...  ...  
995           1736        12  furniture/equipment   31  
996           3857        30                  car   40  
997            804        12             radio/TV   38  
998           1845        45             radio/TV   23  
999           4576        45                  car   27  

[1000 rows x 10 columns]

In [10]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['sex'] = le.fit_transform(data['sex'])
data['housing'] = le.fit_transform(data['housing'])
data['saving_accounts'] = le.fit_transform(data['saving_accounts'])
data['checking_account'] = le.fit_transform(data['checking_account'])
data['purpose'] = le.fit_transform(data['purpose'])
data

risk  sex  job  housing  saving_accounts  checking_account  \
0       1    1    2        1                2                 0   
1       0    0    2        1                0                 1   
2       1    1    1        1                0                 2   
3       1    1    2        0                0                 0   
4       0    1    2        0                0                 0   
..    ...  ...  ...      ...              ...               ...   
995     1    0    1        1                0                 2   
996     1    1    3        1                0                 0   
997     1    1    2        1                0                 2   
998     0    1    2        0                0                 0   
999     1    1    2        1                1                 1   

     credit_amount  duration  purpose  age  
0             1169         6        5   67  
1             5951        48        5   22  
2             2096        12        3   49  
3             7882        42        4   45  
4             4870        24        1   53  
..             ...       ...      ...  ...  
995           1736        12        4   31  
996           3857        30        1   40  
997            804        12        5   38  
998           1845        45        5   23  
999           4576        45        1   27  

[1000 rows x 10 columns]

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
X = data.drop(["risk"],axis=1) # axis: {0 or ‘index’, 1 or ‘columns’}, default 0
y = data[["risk"]]


#train_x, test_x, train_y, test_y
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8, test_size=0.2, random_state=0)
print("Data sucessfully loaded!")

Data sucessfully loaded!


In [12]:
!pip install xgboost

In [13]:
import xgboost
xgboost_model = xgboost.XGBClassifier().fit(X_train, y_train)
y_test_predict = xgboost_model.predict(X_test)
y_test_predict

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1])

In [14]:
# adaptation between tensor to sklearn/pandas
def xgboost_pred(testset):
    probs = xgboost_model.predict_proba(testset[:, :-1])
    return prob.tolist()

import numpy as np

test_examples = np.hstack((X_test,
                           y_test))

In [15]:
test_examples

array([[ 1,  3,  1, ...,  4, 30,  1],
       [ 1,  2,  2, ...,  1, 26,  1],
       [ 1,  2,  1, ...,  4, 43,  1],
       ...,
       [ 0,  1,  1, ...,  3, 39,  1],
       [ 1,  3,  1, ...,  1, 42,  0],
       [ 1,  2,  0, ...,  5, 42,  1]], dtype=int64)

In [16]:
!pip install --upgrade witwidget

In [18]:
from witwidget.notebook.visualization import WitConfigBuilder
config_builder = WitConfigBuilder(
    test_examples.tolist(),
    feature_names=['sex', 'job', 'housing', 'saving_accounts', 'checking_account','credit_amount', 'duration', 'purpose', 'age', 'risk'])\
.set_custom_predict_fn(xgboost_pred).set_target_feature('risk')

In [19]:
from witwidget.notebook.visualization import WitWidget
WitWidget(config_builder, height=600)

WitWidget(config={'model_type': 'classification', 'label_vocab': [], 'feature_names': ['sex', 'job', 'housing'…

# Example 3 - synthetic_credit_card_approval.csv

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("https://raw.githubusercontent.com/manoelgadi/fairdetect/master/datasets/synthetic_credit_card_approval.csv")
df.shape

(500000, 6)

In [22]:
# solution for the need for loggin problem, work with a 10% sample instead the whole 500k rows!

In [23]:
df = df.sample(50000)

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
X = df.drop(["Target"],axis=1) # axis: {0 or ‘index’, 1 or ‘columns’}, default 0
y = df[["Target"]]


#train_x, test_x, train_y, test_y
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8, test_size=0.2, random_state=0)
print("Data sucessfully loaded!")

Data sucessfully loaded!


In [25]:
!pip install xgboost

import xgboost
xgboost_model = xgboost.XGBClassifier().fit(X_train, y_train)
y_test_predict = xgboost_model.predict(X_test)
y_test_predict

array([1, 0, 1, ..., 1, 1, 0])

In [26]:
# adaptation between tensor to sklearn/pandas
def xgboost_pred2(testset):
    probs = xgboost_model2.predict_proba(testset[:, :-1])
    return prob.tolist()

import numpy as np

test_examples = np.hstack((X_test,
                           y_test))

In [27]:
df.columns

Index(['Num_Children', 'Group', 'Income', 'Own_Car', 'Own_Housing', 'Target'], dtype='object')

In [29]:
from witwidget.notebook.visualization import WitConfigBuilder
config_builder = WitConfigBuilder(
    test_examples.tolist(),
    feature_names=['Num_Children', 'Group', 'Income', 'Own_Car', 'Own_Housing', 'Target'])\
.set_custom_predict_fn(xgboost_pred).set_target_feature('Target')

In [30]:
from witwidget.notebook.visualization import WitWidget
WitWidget(config_builder, height=600)

WitWidget(config={'model_type': 'classification', 'label_vocab': [], 'feature_names': ['Num_Children', 'Group'…